name: api
description: A API client library to connect with mscore gateway.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  logging: ^1.0.2
  uuid: ^3.0.5
  localstorage: ^3.0.6
  flutter_bloc: ^8.0.1
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
