version: "3"

services:

  configuration:
    image: ${REPO}/${SOLUTION}-configuration:latest
    container_name: ${SOLUTION}-configuration
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  logger:
    image: ${REPO}/reference-logger:${TAG}
    container_name: ${SOLUTION}-logger
    environment:
      ELASTICSEARCH_HOST: http://index:9092
      KIBANA_HOST: http://dashboard:5601
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./logs:/home/logs
