version: "3"

services:

    registry:
        image: bitnami/zookeeper:3.6.1
        container_name: ${SOLUTION}-registry
        ports:
            - 1001:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    configuration:
        image: ${REPO}/${SOLUTION}-configuration:latest
        container_name: ${SOLUTION}-configuration
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        depends_on:
          - registry

    channel:
        image: bitnami/kafka:2.5.0
        container_name: ${SOLUTION}-channel
        ports:
            - 1002:9092
            - 1003:9093
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=registry:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://channel:9092,PLAINTEXT_HOST://${DOCKER_MACHINE_IP}:${KAFKA_BOOTSTRAP_SERVERS_PORT}
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://channel:9092,PLAINTEXT_HOST://${DOCKER_MACHINE_IP}:${KAFKA_BOOTSTRAP_SERVERS_PORT}
            # - KAFKA_LISTENERS=PLAINTEXT://channel:9092,PLAINTEXT_HOST://${DOCKER_MACHINE_IP}:${KAFKA_BOOTSTRAP_SERVERS_PORT}
            # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://channel:9092,PLAINTEXT_HOST://${DOCKER_MACHINE_IP}:${KAFKA_BOOTSTRAP_SERVERS_PORT}
        depends_on:
            - registry
        volumes:
            - kafkadata:/bitnami/kafka

    rdbms:
        image: postgres:13.2
        container_name: ${SOLUTION}-rdbms
        environment:
            POSTGRES_USER: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        ports:
            - "1004:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init_script/flowable-postgres-init.sql:/docker-entrypoint-initdb.d/flowable-init.sql:ro
            - ./init_script/keycloak-postgres-init.sql:/docker-entrypoint-initdb.d/keycloak-init.sql:ro

    iam:
        image: quay.io/keycloak/keycloak:latest
        container_name: ${SOLUTION}-iam
        ports:
            - 1005:8080
        environment:
            - KEYCLOAK_USER=$KEYCLOAK_USERNAME
            - KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD
            - DB_VENDOR=postgres
            - DB_ADDR=rdbms
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_SCHEMA=keycloak
            - DB_USER=$POSTGRES_USERNAME
            - DB_PASSWORD=$POSTGRES_PASSWORD

volumes:
    pgdata:
        driver: local
    kafkadata:
        driver: local
