version: "3"

services:

    storage:
        image: mongo:4.2.7
        container_name: ${SOLUTION}-storage
        environment:
          - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
          - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        ports:
            - "1006:27017"
        volumes:
            - mongodata:/data/db
            - ./init_script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    index:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: ${SOLUTION}-index
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            - xpack.security.enabled=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            # the `esdata` dir permission should be 777
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 1007:9200

    data:
        image: ${REPO}/${SOLUTION}-data:${TAG}
        container_name: ${SOLUTION}-data
        ports:
            - 2001:2000
        command: java -jar
        stdin_open: true
        tty: true
        depends_on:
            - storage
            - channel
            - index
        volumes:
            - ./logs/data-service:/opt/mscore/logs

    history:
        image: ${REPO}/${SOLUTION}-history:${TAG}
        container_name: ${SOLUTION}-history
        depends_on:
            - channel
        #environment:
        #    JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:5000,server=y,suspend=n
        volumes:
            - ./logs/history-service:/opt/mscore/logs

volumes:
    mongodata:
        driver: local
    esdata:
        driver: local
    dataservice:
        driver: local
    historyservice:
        driver: local
