# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  paths:
      exclude: 
        - README.MD
        - azure-pipelines*

pool:
  vmImage: ubuntu-latest

variables:
  - name: buildNumber
    value: 0
  - name: revision
    value: $[counter(variables['buildNumber'], 1)]

steps:
- task: Bash@3
  name: 'Version'
  displayName: 'Set Tag'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=tag;isOutput=true]$(git describe --tags --abbrev=0)"'

- task: Bash@3
  displayName: 'Print Version'
  inputs:
    targetType: 'inline'
    script: 'echo "$(Version.tag).$(revision)"'

- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: mscore

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy'
    options: -Drevision=$(Version.tag).$(revision)
