# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - mscore/gateway/**
    exclude:
      - mscore/gateway/README.MD
      - mscore/gateway/azure-pipelines*

pool:
  vmImage: ubuntu-latest

variables:
  - name: buildNumber
    value: 0
  - name: revision
    value: $[counter(variables['gateway21'], 1)]

steps:
  - task: Bash@3
    name: "Version"
    displayName: "Set Tag"
    inputs:
      targetType: "inline"
      script: 'echo "##vso[task.setvariable variable=tag;isOutput=true]$(git describe --tags --abbrev=0)"'

  - task: Bash@3
    displayName: "Print Version"
    inputs:
      targetType: "inline"
      script: 'echo "$(Version.tag).$(revision)"'

  # used for mscore profile
  # - task: MavenAuthenticate@0
  #   displayName: 'Maven Authenticate'
  #   inputs:
  #     artifactsFeeds: mscore

  # used for myMavenRepo profile
  - task: DownloadSecureFile@1
    displayName: "Download maven settings file"
    name: "mavenSettingsFile"
    inputs:
      secureFile: "settings.xml"

  - task: Maven@3
    displayName: "Maven build"
    inputs:
      mavenPomFile: "mscore/gateway/pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "mscore/gateway/**/surefire-reports/TEST-*.xml"
      goals: "deploy"
      #    options: -Drevision=$(Version.tag) -Pmscore
      options: -Drevision=$(Version.tag).$(revision) -s $(mavenSettingsFile.secureFilePath) -PmyMavenRepo

  - task: Docker@2
    displayName: "Docker build & push"
    inputs:
      containerRegistry: "Docker Hub - devit16"
      repository: "devit16/mscore-gateway-service"
      command: "buildAndPush"
      Dockerfile: "mscore/gateway/**/service/target/Dockerfile"
      tags: |
        latest
        $(Version.tag).$(revision)
