name: Common 2.0

on:
  workflow_dispatch: # enable manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: >
          [
            {
              "id": "github",
              "username": "${ env.GITHUB_ACTOR }",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }
          ]

    - name: Build with Maven
      run: mvn --file common/pom.xml deploy
