name: Common

on:
  push:
    branches:
      - master
    paths:
      - "mscore/common/**"
      - "!mscore/common/README.MD"
      - "!mscore/common/.gitignore"
  workflow_dispatch: # enable manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        profiles: >
          [
            {
              "id": "useSonar",
              "name": "Profile for Sonarcloud.io",
              "properties": {
                "sonar.login": "${{ secrets.SONAR_LOGIN }}"
              }
            }
          ]

    - name: Build with Maven
      run: mvn --file mscore/common/pom.xml deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
