name: Common action on master branch

on:
  push:
    branches:
      - master
    paths:
      - mscore/common/**
    paths-ignore:
      - mscore/common/README.MD
      - mscore/common/.gitignore

env:
  BUILD_VERSION: 2.1.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        profiles: >
          [
            {
              "id": "useCustomRepo",
              "name": "Profile for custom repostiory",
              "properties": {
                "customRepo.read.url": "${{ secrets.CUSTOMREPO_READ_URL }}",
                "customRepo.write.url": "${{ secrets.CUSTOMREPO_WRITE_URL }}"
              }
            },
            {
              "id": "useSonar",
              "name": "Profile for Sonarcloud.io",
              "properties": {
                "sonar.login": "${{ secrets.SONAR_LOGIN }}"
              }
            }
          ]

    - name: Build with Maven
      run: mvn --file mscore/common/pom.xml -PuseCustomRepo deploy
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: devit16/mscore

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: "mscore/common/docker"
        file: "mscore/common/docker/Dockerfile"
        push: true
        tags: |
          $BUILD_VERSION
          latest
