name: Data Service

on:
  push:
    branches:
      - master
    paths:
      - "data/**"
      - "!data/README.MD"
      - "!data/.gitignore"
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Version'
        required: false
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Latest Tag
      id: latestTag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - name: Set Release Version
      if: ${{ inputs.release }}
      uses: allenevans/set-env@v2.0.0
      with:
        VERSION_NUMBER: ${{ steps.latestTag.outputs.tag }}

    - name: Get Time
      if: ${{ !inputs.release }}
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYYMMDDHHmmss'

    - name: Set Development Version
      if: ${{ !inputs.release }}
      uses: allenevans/set-env@v2.0.0
      with:
        VERSION_NUMBER: ${{ steps.latestTag.outputs.tag }}.${{ steps.time.outputs.time }}-SNAPSHOT

    - name: Print Version Number
      run: echo "Version number is $VERSION_NUMBER"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        profiles: >
          [
            {
              "id": "default",
              "properties": {
                "customRepo.read.url": "${{ secrets.CUSTOMREPO_READ_URL }}",
                "customRepo.write.url": "${{ secrets.CUSTOMREPO_WRITE_URL }}",
                "sonar.login": "${{ secrets.SONAR_LOGIN }}"
              }
            }
          ]
        active_profiles: >
          [
            "default"
          ]
        servers: >
          [
            {
              "id": "github",
              "username": "${ env.GITHUB_ACTOR }",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }
          ]

    - name: Build with Maven
      run: mvn --file data/pom.xml -PuseSonar -Drevision=$VERSION_NUMBER clean deploy sonar:sonar

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: "data/service/target"
        file: "data/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-data:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-data:latest

    - name: Build and push reference docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/data"
        file: "solution/data/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-data:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-data:latest
