name: Tag Release 2.0

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Latest Tag
      id: latestTag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - name: Set Release Version
      uses: allenevans/set-env@v2.0.0
      with:
        VERSION_NUMBER: ${{ steps.latestTag.outputs.tag }}

    - name: Print Version Number
      run: echo "Version number is $VERSION_NUMBER"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        profiles: >
          [
            {
              "id": "default",
              "properties": {
                "customRepo.read.url": "${{ secrets.CUSTOMREPO_READ_URL }}",
                "customRepo.write.url": "${{ secrets.CUSTOMREPO_WRITE_URL }}",
                "sonar.login": "${{ secrets.SONAR_LOGIN }}"
              }
            }
          ]
        active_profiles: >
          [
            "default"
          ]
        servers: >
          [
            {
              "id": "github",
              "username": "${ env.GITHUB_ACTOR }",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }
          ]

    - name: Build with Maven
      run: mvn --file pom.xml -Drevision=$VERSION_NUMBER clean deploy

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker data image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "data/service/target"
        file: "data/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-data:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-data:latest

    - name: Build and push reference data service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/data"
        file: "solution/data/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-data:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-data:latest

    - name: Build and push Docker gateway image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "gateway/service/target"
        file: "gateway/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-gateway:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-gateway:latest

    - name: Build and push reference gateway service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/gateway"
        file: "solution/gateway/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-gateway:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-gateway:latest

    - name: Build and push Docker history image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "history/service/target"
        file: "history/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-history:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-history:latest

    - name: Build and push reference history service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/history"
        file: "solution/history/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-history:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-history:latest

    - name: Build and push Docker notification image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "notification/service/target"
        file: "notification/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-notification:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-notification:latest

    - name: Build and push reference notification service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/notification"
        file: "solution/notification/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-notification:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-notification:latest

    - name: Build and push Docker workflow image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "workflow/service/target"
        file: "workflow/service/target/Dockerfile"
        push: true
        tags: |
          dkakunsi/mscore-workflow:${{ env.VERSION_NUMBER }}
          dkakunsi/mscore-workflow:latest

    - name: Build and push reference workflow service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/workflow"
        file: "solution/workflow/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-workflow:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-workflow:latest

    - name: Build and push reference logger service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/logger"
        file: "solution/logger/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-log:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-log:latest

    - name: Init configuration file
      working-directory: solution/configuration
      run: bash ./load.sh > ./init

    - name: Build and push reference configuration service docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: "solution/configuration"
        file: "solution/configuration/Dockerfile"
        push: true
        tags: |
          dkakunsi/reference-configuration:${{ env.VERSION_NUMBER }}
          dkakunsi/reference-configuration:latest
